### ISSUE TITLE
harpoon sprite held weirdly in third person

### ISSUE THREAD

**Issue by DoomRater** [ACGaming/deadly-monsters#2]
With the left hand we see this:
![2021-09-07_07 54 44](https://user-images.githubusercontent.com/4010432/132340557-31af6baa-9b88-4a8b-bf77-36069ecdeebd.png)
In the right hand we see this:
![2021-09-07_07 56 04](https://user-images.githubusercontent.com/4010432/132340576-b84bde7f-3d05-4ebe-9a0f-54e79c28408b.png)
And here's what it seems like it should look like in first person (held in the left hand):
![2021-09-07_07 55 35](https://user-images.githubusercontent.com/4010432/132340642-b5f1b8cb-63b0-4845-b096-2521fe71a91a.png)

This isn't just a result of using First Person View mod, this also happens in F5 mode.
![2021-09-07_07 54 49](https://user-images.githubusercontent.com/4010432/132340736-2df846b7-14a3-497e-97c6-c84094f69695.png)

**Comment by ACGaming** [comment]
One could argue that it faces the wrong way now, but yeah. Best I can do with the current texture.
