### ISSUE TITLE
Haunted Cows still resetting time

### ISSUE THREAD

**Issue by DoomRater** [ACGaming/deadly-monsters#4]
In Deadly Monsters 1.9.0 I am noticing time reset to Day 1 when I am hit by Haunted Cow.  This is resetting my progress on Hostile Worlds: Invasions and making the mod trivial to cheese.  I didn't report earlier because I didn't notice until after installing a mod that allows me to see the current day.

Using the Sunlight Drop also seems to change the day to Day 2.

I used Time HUD 7.3.1 to see what day the game is in, but originally was using Better HUD before I ran into OpenGL errors that forced me to stop using it until I can locate what minimum conditions I need to report that.

**Comment by ACGaming** [comment]
You're absolutely right, I completely missed the other two cases of time changes. Hotfix coming soon!

**Comment by DoomRater** [comment]
Oh wow you even factored in doDaylightCycle gamerules in your logic.  Can't wait to fear haunted cows even more than I already do!

**Comment by ACGaming** [comment]
I bet! 😏
