### ISSUE TITLE
Morphic Tool from Thaumic Augmentation triggers wrong weapon time skip on cows

### ISSUE THREAD

**Issue by DoomRater** [ACGaming/deadly-monsters#5]
This is a bit of an awkward issue.  Thaumic Augmentation adds a tool called the Morphic Tool that can allow the skin of any item to become the physical item model for any other tool.  The problem arises when I morph a sword into another sword, say making a powerful Obsidian Sword from Toroquest look like Twilight Forest's Glass Sword.  Because the Morphic Tool isn't on the list of items to check, killing a Haunted Cow with this tool will skip to night.

I'm not sure how to best determine if the Morphic Tool is actually a sword class item though.

**Comment by DoomRater** [comment]
On second observation, it appears Morphic Tools that are swords morphed into swords don't entirely behave like swords either.  This could actually be on Thaumic Augmentation's end.  Codex has made similar mistakes with the Primal Cutter implementation.

**Comment by ACGaming** [comment]
I could just implement a simple whitelist to define valid weapons.

**Comment by DoomRater** [comment]
Actually yeah that doesn't overcomplicate things too much.
