### ISSUE TITLE
Deadly monsters can spawn in Mushroom Islands

### ISSUE THREAD

**Issue by DoomRater** [ACGaming/deadly-monsters#6]
I don't know if this was intended by the original author or not, but monsters spawning in Mushroom Islands is a violation of one of the hidden rules of Minecraft: no hostiles should spawn there.

It's already crazy that they spawn in the end as much as they do, really spices up that dimension.  But I think some control over what biomes and dimensions they're allowed to spawn in would be nice.

**Comment by ACGaming** [comment]
Thanks for another issue report! Nether, end and mushroom biomes were never intended, the checks were just wrong.
