### ISSUE TITLE
Sunlight drop trivializes Hostile Worlds Invasion Nights

### ISSUE THREAD

**Issue by DoomRater** [ACGaming/deadly-monsters#7]
Hostile Worlds Invasions tries its best to prevent time changing events like bed sleeping and whatnot to prevent players from skipping the invasion night.  However, using a Sunlight Drop trivializes this as it just skips straight to morning.  The morning after.

What if it skipped to the beginning of the previous day instead?  The alternative is realizing when an invasion night is for players on a server and refusing to do anything during that point, but going back a day would result in someone running headfirst into the invasion as soon as it was night again.

My only two workarounds right now are disable time skipping (again) or LootTweaking out the Sunlight Drops from Haunted Cows.

**Comment by ACGaming** [comment]
Sorry for taking over a month for this trivial change! 🙃
This actually saved 3 bytes of the mod size. 👀
